version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    container_name: psql
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=admin
      - POSTGRES_DB=pdf
    volumes:
      - psql_db:/var/lib/db/psql
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  psql_db:
